### ISSUE TITLE
[Feature Request] Add URL option

### ISSUE THREAD

**Issue by raf555** [TheRealBarenziah/imgbb-uploader#11]
Any plan to add url option support? Because imgbb supports url as argument.

**Comment by TheRealBarenziah** [comment]
Hello !
Thank you for the suggestion, it should indeed be supported here too!
Leaving this issue open 'til it is done (this weekend if everything goes well)

**Comment by raf555** [comment]
Thank you! I will gladly wait!

**Comment by TheRealBarenziah** [comment]
[This is now possible](https://github.com/TheRealBarenziah/imgbb-uploader/blob/master/src/validateInput.ts#L48), thanks again for your suggestion & patience :)

**Comment by cmoskvitin** [comment]
Bro, your library just saved some valuable time for me, namely this url upload feature. Thanks a lot!
