### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by ShinNouzen** [TheRealBarenziah/imgbb-uploader#17]
Can the image be buffer?

**Comment by TheRealBarenziah** [comment]
Hello Shineilchijo,

sorry for being late; as I hope you've figured, this module doesn't support Buffer as input. 

However, luckily the nodejs `Buffer` gives us [.toString()](https://nodejs.org/api/buffer.html#buftostringencoding-start-end) method, so you only need to (example stolen [here](https://stackabuse.com/encoding-and-decoding-base64-strings-in-node-js/)):

```javascript
let data = 'stackabuse.com';
let buff = new Buffer(data);
let base64data = buff.toString('base64');
```
Then this `base64data` can be passed  to imgbb-uploder `options.base64string` without problem. :+1:
