### ISSUE TITLE
Is it possible to put an image in a specific album ?

### ISSUE THREAD

**Issue by Aurelien-Dev** [TheRealBarenziah/imgbb-uploader#35]
Hello,

Is it possible to put an image in a specific album ?

Thanks

**Comment by TheRealBarenziah** [comment]
Hello Aurelien,

afaik it's not possible with their public API, only with their GUI. If you need more programmatic freedom (and don't want to implement an album feature yourself with some DB), another service like [imgur](https://apidocs.imgur.com/) should be more suitable for you.
