### ISSUE TITLE
Quick Question about names/albums.

### ISSUE THREAD

**Issue by swork1** [TheRealBarenziah/imgbb-uploader#4]
Is there a way to upload the images with a specific name or in a specific album?

The names are currently just random numbers and letters. (on the website)

Thanks!

**Comment by TheRealBarenziah** [comment]
Hello !

[Their endpoint accepts an optional](https://api.imgbb.com/) `name` parameter, so this part shouldn't be hard. I'll look into it eventually.  

About specific albums, afaik it isn't feasible with their public API.  

ImgBB is nice for easy and quick hosting, but it isn't really suited for media management. If you need that, the [imgur API](https://api.imgur.com/endpoints) seem like a good, free alternative with far more tools available than the single imgBB endpoint.

**Comment by swork1** [comment]
Ok thanks!
