### ISSUE TITLE
support img as base64 or binary instead of only a path to a stored img

### ISSUE THREAD

**Issue by mirsella** [TheRealBarenziah/imgbb-uploader#6]
afaik with this package it is only possible to upload img by providing their path on the disk.
it would be useful if we could provide the img as base64 or binary like imgbb support.
I'll stick to axios for the time being as i don't want to save a picture even if it's for deleting it after.

thanks

**Comment by TheRealBarenziah** [comment]
Hello, that's an awesome feature suggestion, thank you!

Should be pretty trivial considering I'm already turning the file into base64 (so basically, already sending base64 string to imgBB)

Please leave this open 'til I patch

**Comment by mirsella** [comment]
thanks, that a quick consumer services :)

**Comment by TheRealBarenziah** [comment]
Thanks again for your suggestion, [it should now be feasible](https://github.com/TheRealBarenziah/imgbb-uploader/commit/6dc38f3c8528a97cb92c1c56b9b6381f0e72592b) !
